---
title: "CovidProject"
author: "Peter McClintock"
date: "22/08/2021"
output: html_document
---


# Data
The data was sourced from OurWorldInData which provides up to date COVID data ranging from vaccination amounts to death counts. From the one file I created two separate excel files and imported them into Microsoft SQL Server which is what I used for the data manipulation.

# SQL

Below is the code for my initial dive into the database.

```{sql, eval=FALSE}
-- Select * From CovidDeathsProject..CovidDeaths order by 3,4

-- Select Data that we are going to be using
Select Location, date, total_cases, new_cases, total_deaths, population
FROM CovidDeathsProject..CovidDeaths
order by 1,2

-- Looking at Total Cases vs Total Deaths
-- Likelihood of dying if you contract the virus in your country
Select Location, date, total_cases, total_deaths, (total_deaths/total_cases)*100 as DeathPercentage
FROM CovidDeathsProject..CovidDeaths
Where location like '%states%'
order by 1,2

-- Looking at Total Cases vs Population
Select Location, date, total_cases, population, (total_cases/population)*100 as CasesPerPopulation
FROM CovidDeathsProject..CovidDeaths
Where location like '%Kingdom%'
order by 1,2

-- Looking at countries with highest infection rate compared to population
Select Location, MAX(total_cases) as HighestInfectionCount, MAX((total_cases/population))*100 as PercentPopulationInfected
FROM CovidDeathsProject..CovidDeaths
Group by location, population
order by PercentPopulationInfected desc

-- Showing countries with highest death count per population
-- we cast because the total deaths is an nvarchar not an int
Select location, MAX(cast(total_deaths as int)) as TotalDeathCount
FROM CovidDeathsProject..CovidDeaths
Where continent is not null
Group by location
order by TotalDeathCount desc

-- Showing highest deaths by continent
Select continent, MAX(cast(total_deaths as int)) as TotalDeathCount
FROM CovidDeathsProject..CovidDeaths
Where continent is not null
Group by continent
order by TotalDeathCount desc


-- Global Death Percentage per cases
Select SUM(new_cases) as total_cases, SUM(cast(new_deaths as int)) as total_deaths, SUM(cast(new_deaths as int))/SUM(new_cases) * 100 as DeathPercentage
From CovidDeathsProject..CovidDeaths
where continent is not null
-- Group by date
order by 1,2


-- Looking at Total population Vs vaccinations
Select dea.continent, dea.location, dea.date, dea.population, vac.new_vaccinations
, Sum(Cast(vac.new_vaccinations as int)) OVER (Partition by dea.location Order by dea.location, dea.date) as RollingPeopleVaccinated
From CovidDeathsProject..CovidDeaths dea
Join CovidDeathsProject..CovidVaccinations vac
On dea.location = vac.location
and dea.date = vac.date
Where dea.continent is not null
order by 2,3


-- using a CTE
With PopvsVac (Continent, Location, Date, Population, new_vaccinations, RollingPeopleVaccinated) as 
(
Select dea.continent, dea.location, dea.date, dea.population, vac.new_vaccinations,
Sum(Convert(int,vac.new_vaccinations)) OVER (Partition by dea.location Order by dea.location, dea.date) as RollingPeopleVaccinated
From CovidDeathsProject..CovidDeaths dea
Join CovidDeathsProject..CovidVaccinations vac
On dea.location = vac.location
and dea.date = vac.date
Where dea.continent is not null
)
Select *, (RollingPeopleVaccinated/Population)*100
From PopvsVac
Where location like '%kingdom%'
order by 2,3

-- using a temp table
Drop table if exists #PercentPopulationVaccinated
Create Table #PercentPopulationVaccinated
(Continent nvarchar(255), Location nvarchar(255), Date datetime, Population numeric, new_vaccinations numeric, RollingPeopleVaccinated numeric)

Insert into #PercentPopulationVaccinated
Select dea.continent, dea.location, dea.date, dea.population, vac.new_vaccinations,
Sum(Convert(int,vac.new_vaccinations)) OVER (Partition by dea.location Order by dea.location, dea.date) as RollingPeopleVaccinated
From CovidDeathsProject..CovidDeaths dea
Join CovidDeathsProject..CovidVaccinations vac
On dea.location = vac.location
and dea.date = vac.date
Where dea.continent is not null

Select *, (RollingPeopleVaccinated/Population)*100
From #PercentPopulationVaccinated
Where location like '%kingdom%'
order by 2,3


-- Creating a view to store data for later visualisations
Create View PercentPopulationVaccinated as
Select dea.continent, dea.location, dea.date, dea.population, vac.new_vaccinations,
Sum(Convert(int,vac.new_vaccinations)) OVER (Partition by dea.location Order by dea.location, dea.date) as RollingPeopleVaccinated
From CovidDeathsProject..CovidDeaths dea
Join CovidDeathsProject..CovidVaccinations vac
On dea.location = vac.location
and dea.date = vac.date
Where dea.continent is not null

```


From this initial look, I moved on to create four queries which I would take further to present some findings. These are included below as well.

```{sql, eval=FALSE}
-- Queries for tableau visualisation

-- 1. Total deaths to cases ratio

Select SUM(new_cases) as total_cases, SUM(CAST(new_deaths as int)) as total_deaths, SUM(CAST(new_deaths as int)) * 100 / SUM(new_cases) as DeathPercentage
From CovidDeathsProject..CovidDeaths
where continent is not null
order by 1,2


-- 2. Continent total death count
Select location, SUM(CAST(new_deaths as int)) as TotalDeathCount
From CovidDeathsProject..CovidDeaths
Where continent is null and location not in ('World', 'European Union', 'International')
Group by location
order by TotalDeathCount desc

-- 3. total worst percentage of population infected per country
Select location, population, Max(total_cases) as HighestInfectionCount, Max((total_cases/population)) * 100 as PercentPopulationInfected
From CovidDeathsProject..CovidDeaths
Group by location, population
order by PercentPopulationInfected desc


-- 4. Countries ranked by percent of population infected by date
Select location , population, date, Max(total_cases) as HighestInfectionCount, Max((total_cases/population))*100 as PercentPopulationInfected
From CovidDeathsProject..CovidDeaths
Group by location, population, date
order by PercentPopulationInfected desc
```

## Tableau Data

* Query 1 looks at the percentage of people who died compared to the total number of cases. It shows the likelihood of death upon catching the virus on average. To calculate the totals the new_deaths field had to be converted from a nvarchar to an int. The data also includes not just countries but continent totals. However, I wanted to look at the breakdown from countries included. That is why the where continent is null condition is included. 
* Query 2 follows a similar vein but congregates the countries into their continents and looks at total death rates per continent. 
* Query 3 takes the highest infection count of each country and calculates the worst infection rate per country. 
* Finally, query 4 takes the same data but includes the data as a time series.

# Tableau Public
Due to Tableau public's lack of ability to connect to databases in sql, I exported the tables from the queries to excel and imported it into Tableau through excel. From this I created a series of graphics and the below dashboard shows the final product.


<iframe src="https://public.tableau.com/views/CovidDashboardProject_16296348960110/Dashboard1?:language=en-US&:display_count=n&:origin=viz_share_link"
 width="1000" height="800"></iframe>
