---
title: "__CV__"
---

# Peter McClintock

## Education
### MScs Quantitative Finance (2020/2021)
#### Queen's University Belfast
Some of the key skills learned from the course

* Asset Pricing: Stock analysis and reporting using Bloomberg
*	Econometrics: Regression analysis using R
*	Data Management: Big Data discussion, and implementing data management and analysis practices using SQL and R
*	Machine Learning: Model building in R, using machine learning to solve and analyse business problems including, Decision Trees, Random Forests, GBMs
*	Finance in Python: Implementation of computational methods in Python applied to financial problems. Monte Carlo simulation, finite differencing, tree pricing options, Newton-Raphson.
*	Time-Series: Analysing time series data using traditional econometric techniques with the aim of producing and interpreting statistical results. Regression, ARIMA models, forecasting of results
*	Investing practices: Machine learning used to help financial problems. Denoising and detoning matrices, modelling using logistic regression, decision trees, and random forests, grouping data through clustering, calculating entropy.
*	Group work: Partner with classmates to help complete projects more efficiently with a higher standard

### BSc Finance 2:1 (2016/2020)
#### Queen's University Belfast
Key skills and results of the course

*	Research project on the effects of CEO compensation packages on US firm performance analysed using R studio
*	Econometrics module with projects using R studio to analyse and complete basic modelling of stock prices, through GARCH and ARIMA

### St. Louis Grammar School Ballymena (2009/2016)
A Level: A* A* B                 GCSE: Five A* and five A grades

## Employment Experience
### Pensions Analyst (2018/2019)
For the placement year of the degree, I was based in Mercer, a pensions company and I was focused on valuing French pensions. Core responsibilities included.

*	Analysis and manipulation of data
*	Data visualisation working with the French Consultants
*	Creating end of year liabilities reports
*	Reconciliation of data from year to year, and insights into customer churn
Carphone Warehouse 									2019/2020
Provided great customer support and advice in store to customers allowing an easy stress-free experience when buying a phone. Skills developed in the job include.
*	Communication: Being able to work quickly to find exactly what a customer wants to keep them as happy as possible
*	I.T. skills: Working through contracts and transactions on the systems instore. As well as this designing an excel spreadsheet to show how employees should be meeting targets.
*	Teamwork: Providing help for staff during important sales, giving feedback as a team to improve sales.
*	Management: Locking up the store at the end of shifts and making sure it was ready for the next day

## Skills								         

* Proficient in R Studio
* Python
* Highly proficient in Excel 
* Unity Game Development Course for C# Programming					          
* Unity C# Multiplayer Game Course
* Microsoft Access & SQL
* Proficient in Bloomberg

Other Awards/Achievements

* Grade 8 Clarinet and Piano
* Top music student St. Louis Grammar
* Volunteering experience in a primary school orchestra
 				
