---
title: "__My Website__"
output:
  html_document:
    includes:
      in_header:
      - header.html
      - hero-image.html
---


## About

Hey! I am a masters student interested in the world of data science. Through my course I have learnt how to analyse and discover new information using R, Python and SQL. I would be strongest in R but continue to work on my ability in python and SQL as this website should show.

I have strong Excel skills from my time in industry working as a data analyst. I worked for a placement year in university at Mercer, where my day to day involved complex pensions formula and large workbooks. Due to this I have good problem solving a trouble shooting skills in Excel. Similarly, a mixture of the master’s course and remote learning has meant that several projects completed this year have required a large amount of independent problem-solving skills.

In report generation, all the projects that I worked on were completed through R Markdown. Through this data visualisation and a professional look were the goal. The reports produced were a mixture of pdf, word documents and html files. Each with incorporated graphs and tables which were easily reproducible in the event of changing data. As an extension of this outside the course I have created this website using R markdown and the reports are included with the source code.

